server:
  port: 8080
spring:
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8
    excluded-view-names: ''
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  datasource:
    username: root
    password: 22rabBIThole
    url: jdbc:mysql://localhost:3306/j2ee?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&tinyInt1isBit=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始化连接数量
      initial-size: 5
      # 最小线连接数量
      min-idle: 5
      # 最大连接数量
      max-active: 20
      # 获取连接时最大等待时间，单位毫秒
      max-wait: 60000
      #销毁线程时检测当前连接的最后活动时间和当前时间差大于该值时，关闭当前连接
      min-evictable-idle-time-millis: 30000
      #用来检测连接是否有效的sql 必须是一个查询语句
      #mysql中为 select 'x'
      #oracle中为 select 1 from dual
      validation-query: select 'x'
      #申请连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-borrow: false
      #归还连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为tru
      test-on-return: false
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      # 配置监拉统计挡成的filters. stat: 监控统计、Log4j:日志记录、waLL: 防御sqL注入
      filters: stat,wall,log4j2
      # 配置后台监控
      stat-view-servlet:
        # 允许访问的地址，这里因为时本地所以配置当前机器
        allow: 127.0.0.1
        # 是否开启访问
        enabled: true
        # 是否能够重置数据
        reset-enable: false
        # 管理页面登陆的用户名
        login-username: admin
        # 管理页面登陆的密码
        login-password: admin

mybatis:
  # 配置mapper
  mapper-locations: classpath:mappers/*.xml
  # 注册实体类
  type-aliases-package: com.smart.water.entity
  configuration:
    # 开启驼峰映射
    map-underscore-to-camel-case: true
    # 查看SQL日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl